version: '3'

services:
  website:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    image: hubrise/website-dev
    container_name: website_test
    volumes:
      - .:/var/www/website
    command: /usr/local/bin/yarn test:all:ci