version: '3'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: hubrise/website
    container_name: website_prod
    volumes:
      - .:/var/www/website
    ports:
      - "8001:8000"
