version: '3'

services:
  website:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    image: hubrise/website-dev
    container_name: website
    volumes:
      - .:/var/www/website
    ports:
      - "8000:8000"
