kind: Deployment
apiVersion: apps/v1

metadata:
  name: website

spec:
  replicas: 2

  template:
    spec:
      containers:
        - name: website
          # We use the ":latest" image
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 30m
              memory: 80Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: RECAPTCHA_SITE_KEY
              value: 6LfjbNYUAAAAAPx_tCv_YyhueK2JIjf58b2HGU8d
            - name: CONTACT_MESSAGE_URL
              value: https://manager.staging-hubrise.com/api/contact_message
